import { App } from './app/App'
import { CustomizeContacts } from './customize-contacts/customize-contacts'
import { HeaderMenu } from './header-menu/header-menu'
import { MainSlider } from './main-slider/main-slider'
import { OurStrength } from './our-strength/our-strength'
import { BusinessSupport } from './business-support/business-support'
import { MainActivity } from './main-activity/main-activity'
import { StaffSlider } from './staff-slider/staff-slider'
import { PartnerReviews } from './partner-reviews/partner-reviews'
import { OurPractice } from './our-practice/our-practice'
import { ServiceList } from './service-list/service-list'
import { WhyTrustUs } from './why-trust-us/why-trust-us'
import { OurAdvantages } from './our-advantages/our-advantages'
import { CooperationStart } from './cooperation-start/cooperation-start'
import { ServicesPrice } from './services-price/services-price'
import { FooterContacts } from './footer-contacts/footer-contacts'
import { ScrollToTop } from './scroll-to-top/scroll-to-top'

export { App, CustomizeContacts, HeaderMenu, MainSlider, OurStrength, BusinessSupport, MainActivity, StaffSlider, PartnerReviews, OurPractice, ServiceList, WhyTrustUs, OurAdvantages, CooperationStart, ServicesPrice, FooterContacts, ScrollToTop }